# Copyright (C) 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from tests.mocks.mock_products import (
    grpc_mock_product_pb2 as tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2,
)


class GrpcMockProductStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/GetVersion",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.FromString,
        )
        self.GetProperty = channel.unary_unary(
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/GetProperty",
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.FromString,
        )
        self.SetProperty = channel.unary_unary(
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/SetProperty",
            request_serializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.StoreStateGivenAbsoluteFilePath = channel.unary_unary(
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/StoreStateGivenAbsoluteFilePath",
            request_serializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.RestoreStateGivenAbsoluteFilePath = channel.unary_unary(
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/RestoreStateGivenAbsoluteFilePath",
            request_serializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class GrpcMockProductServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SetProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StoreStateGivenAbsoluteFilePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RestoreStateGivenAbsoluteFilePath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_GrpcMockProductServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetVersion": grpc.unary_unary_rpc_method_handler(
            servicer.GetVersion,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.SerializeToString,
        ),
        "GetProperty": grpc.unary_unary_rpc_method_handler(
            servicer.GetProperty,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.SerializeToString,
        ),
        "SetProperty": grpc.unary_unary_rpc_method_handler(
            servicer.SetProperty,
            request_deserializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "StoreStateGivenAbsoluteFilePath": grpc.unary_unary_rpc_method_handler(
            servicer.StoreStateGivenAbsoluteFilePath,
            request_deserializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        "RestoreStateGivenAbsoluteFilePath": grpc.unary_unary_rpc_method_handler(
            servicer.RestoreStateGivenAbsoluteFilePath,
            request_deserializer=tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "tests.mocks.grpc_mock_product.GrpcMockProduct", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class GrpcMockProduct(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVersion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/GetVersion",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetProperty(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/GetProperty",
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def SetProperty(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/SetProperty",
            tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def StoreStateGivenAbsoluteFilePath(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/StoreStateGivenAbsoluteFilePath",
            tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def RestoreStateGivenAbsoluteFilePath(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/tests.mocks.grpc_mock_product.GrpcMockProduct/RestoreStateGivenAbsoluteFilePath",
            tests_dot_mocks_dot_mock__products_dot_grpc__mock__product__pb2.StringMessage.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
