# Copyright (C) 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: tests/mocks/mock_products/grpc_mock_product.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n1tests/mocks/mock_products/grpc_mock_product.proto\x12\x1dtests.mocks.grpc_mock_product\x1a\x1bgoogle/protobuf/empty.proto"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x01(\t2\xed\x03\n\x0fGrpcMockProduct\x12T\n\nGetVersion\x12\x16.google.protobuf.Empty\x1a,.tests.mocks.grpc_mock_product.StringMessage"\x00\x12U\n\x0bGetProperty\x12\x16.google.protobuf.Empty\x1a,.tests.mocks.grpc_mock_product.StringMessage"\x00\x12U\n\x0bSetProperty\x12,.tests.mocks.grpc_mock_product.StringMessage\x1a\x16.google.protobuf.Empty"\x00\x12i\n\x1fStoreStateGivenAbsoluteFilePath\x12,.tests.mocks.grpc_mock_product.StringMessage\x1a\x16.google.protobuf.Empty"\x00\x12k\n!RestoreStateGivenAbsoluteFilePath\x12,.tests.mocks.grpc_mock_product.StringMessage\x1a\x16.google.protobuf.Empty"\x00\x62\x06proto3'
)


_STRINGMESSAGE = DESCRIPTOR.message_types_by_name["StringMessage"]
StringMessage = _reflection.GeneratedProtocolMessageType(
    "StringMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _STRINGMESSAGE,
        "__module__": "tests.mocks.mock_products.grpc_mock_product_pb2",
        # @@protoc_insertion_point(class_scope:tests.mocks.grpc_mock_product.StringMessage)
    },
)
_sym_db.RegisterMessage(StringMessage)

_GRPCMOCKPRODUCT = DESCRIPTOR.services_by_name["GrpcMockProduct"]
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _STRINGMESSAGE._serialized_start = 113
    _STRINGMESSAGE._serialized_end = 143
    _GRPCMOCKPRODUCT._serialized_start = 146
    _GRPCMOCKPRODUCT._serialized_end = 639
# @@protoc_insertion_point(module_scope)
