documentation:
  - '.github/workflows/_doc.yml'
  - 'doc/**'
  - 'pyproject.toml'
  - 'uv.lock'
  - 'packages/**/doc/**'
  - 'packages/bdm-python-api/poetry.lock'
  - 'packages/dash-super-components/poetry.lock'
  - 'packages/glow-engine/poetry.lock'
  - 'packages/saf-iam-oidc/poetry.lock'
  - 'packages/saf-product-configuration/poetry.lock'
  - 'packages/saf-product-manager/poetry.lock'
