[tox]
description = Default tox environments list
envlist =
    style
    tests
    doc-{links,html,pdf}
    dist
skip_missing_interpreters = true
isolated_build = true
isolated_build_env = build

[testenv]
description = Checks for project unit tests and coverage (if desired)
basepython =
    tests311: python3.11
    tests312: python3.12
    tests313: python3.13
    tests314: python3.14
    {style,tests,doc,dist}: python3
setenv =
    PYTHONUNBUFFERED = yes
allowlist_externals =
    poetry

[testenv:tests]
description = Checks for project unit tests and coverage (if desired)
basepython =
    tests311: python3.11
    tests312: python3.12
    tests313: python3.13
    tests314: python3.14
    {style,tests,doc,dist}: python3
setenv =
    PYTHONUNBUFFERED = yes
    coverage: PYTEST_EXTRA_ARGS = --cov=ansys.saf.product_configuration --cov-report=term --cov-report=xml:.cov/xml --cov-report=html:.cov/html
allowlist_externals =
    poetry
commands_pre =
    poetry install --with tests
commands =
    pytest {env:PYTEST_MARKERS:} {env:PYTEST_EXTRA_ARGS:} {posargs:-vv}

[testenv:style]
description = Checks project code style
commands_pre =
    poetry install --with tests,doc --all-extras
deps =
    pre-commit
commands =
    pre-commit install
    pre-commit run --all-files

[testenv:doc-{clean,links,html,pdf}]
description =
    clean: Clean rendered documentation
    links: Check documentation links
    html: Build HTML documentation
    pdf: Build PDF documentation
allowlist_externals =
    poetry
    pdflatex
commands_pre =
    poetry install --with doc
recreate = false
setenv =
    SOURCE_DIR = doc/source
    BUILD_DIR = doc/_build
    STATIC_DIR = doc/source/_static
    links: BUILDER = linkcheck
    html: BUILDER = html
    pdf: BUILDER = latex
    links,html,pdf: BUILDER_OPTS = --color -v -j auto -W --keep-going
commands =
    clean: sphinx-build -M clean "{toxinidir}" "{toxinidir}/{env:BUILD_DIR}"
    links,html,pdf: sphinx-build -d "{toxworkdir}/doc_doctree" {env:SOURCE_DIR} "{toxinidir}/{env:BUILD_DIR}/{env:BUILDER}" {env:BUILDER_OPTS} -b {env:BUILDER}
    pdf: pdflatex -interaction=nonstopmode -output-directory="{toxinidir}/{env:BUILD_DIR}/{env:BUILDER}" {toxinidir}/{env:BUILD_DIR}/{env:BUILDER}/ansys-saf-sdk-testing.tex

[testenv:dist]
description = Build wheel and source distribution artifacts
skip_install = true
allowlist_externals =
    poetry
commands_pre =
    poetry install
commands =
    poetry build
