# Copyright (C) 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from collections.abc import Callable
from typing import Any

from pydantic import TypeAdapter, ValidationError

from ansys.saf.glow._core.client_exceptions import BadRequestException
from ansys.saf.glow._core.gql import GqlClientConnectionPool, get_update_project_steps_request_str
from ansys.saf.glow._core.step_model import StepModel
from ansys.saf.glow._hps_parametric_studies.base import DynamicHpsProject


def perform_update_via_graphql(
    graphql_client: GqlClientConnectionPool,
    step_type: type[StepModel],
    step_name: str,
    json_field_data: dict[str, Any],
    project_id: str,
    fetch_field_value: Callable[[str], Any],
    exception_mapper: Callable[[str], Exception],
):
    """a helper function to perform GraphQL updates for project steps.

    Parameters
    ==========
    graphql_client: GqlClientConnectionPool
        The GraphQL client connection pool to use for the update.
    step_type: type[StepModel]
        The type of the step being updated.
    step_name: str
        The name of the step being updated.
    json_field_data: dict[str, Any]
        The data to use for the update which has been mapped using ``jsonable_encoder``
    project_id: str
        The ID of the project being updated.
    fetch_field_value: Callable[[str], Any]
        A function to fetch the original python value of a field in json_field_data.
    exception_mapper: Callable[[str], Exception]
        A function to map validation errors to exception objects.
    """
    update_project_request_str = get_update_project_steps_request_str(json_field_data, project_id, step_name)
    if update_project_request_str:
        try:
            graphql_client.run_query(update_project_request_str, payload=json_field_data)
        except BadRequestException as e:
            # following checks whether the original values that we are setting are consistent with the step
            # the check generates a human friendly exception appropriate to the context
            # the reason for doing this is because
            # (a) when the value is a pydantic model object the error message is not very helpful see
            # test_passing_incorrect_values_for_multiple_fields_to_graphql_end_point_results_in_full_pydantic_message
            # see test_set_step_invalid_model_type_value_raises_understandable_bad_request_exception for
            # an example of the more informative error message generated by this method
            # (b) in some contexts a BadRequestException is not appropriate and a Malformed Solution Exception is more
            # suitable

            # We perform per field testing because GLOW specifically doesn't support
            # cross field validation in the server and we match that behavior here in the client.

            errors: list[str] = []
            for field_name in json_field_data:
                step_dict: dict[str, Any] = {}
                raw_value = fetch_field_value(field_name)
                field_value = raw_value.persisted_project if isinstance(raw_value, DynamicHpsProject) else raw_value
                step_dict[field_name] = field_value
                try:
                    TypeAdapter(step_type).validate_python(step_dict)
                except ValidationError as validation_error:
                    errors.append(str(validation_error))
            if errors:
                raise exception_mapper("\n".join(errors)) from e
            raise
