repos:

  - repo: https://github.com/psf/black
    rev: 3702ba224ecffbcec30af640c149f231d90aebdb # 24.4.2
    hooks:
      - id: black
        files: ^examples/
        args: ["--config=examples/pyproject.toml"]

  - repo: https://github.com/pycqa/isort
    rev: c655831799765e9593989ee12faba13b6ca391a5 # 5.13.2
    hooks:
      - id: isort
        files: ^examples/
        args: ["--settings-path=examples"]

  - repo: https://github.com/PyCQA/flake8
    rev: 88a4f9b2f48fc44b025a48fa6a8ac7cc89ef70e0 # 7.0.0
    hooks:
      - id: flake8
        files: ^examples/
        exclude: "^examples/tests/"
        args: ["--config=examples/.flake8"]

  - repo: https://github.com/codespell-project/codespell
    rev: 193cd7d27cd571f79358af09a8fb8997e54f8fff # v2.3.0
    hooks:
      - id: codespell
        files: ^examples/
        args: ["--skip", "*doc/styles/*,*.js,*.tmp,*.vtu,*poetry.lock", "--ignore-words",
          "doc/styles/Vocab/ANSYS/accept.txt,examples/.codespell.ignore"]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 07f6707e2c5612960347f7c00125620457f490a7 # 6.3.0
    hooks:
      - id: pydocstyle
        files: ^examples/
        additional_dependencies: [toml]
        exclude: "^examples/tests/"
        args: ["--config=examples/pyproject.toml"]

  - repo: https://github.com/python-poetry/poetry
    rev: a84cd0f1bedb5769ef6ef7389d8ee99b93b9ba4c # frozen: v2.3.2
    hooks:
      - id: poetry-check
        name: poetry-check (examples)
        entry: poetry -C examples check
        files: "^examples/(pyproject\\.toml|poetry\\.lock)$"
        pass_filenames: false

  - repo: https://github.com/gitleaks/gitleaks
    rev: 6eaad039603a4de39fddd1cf5f727391efe9974e # v8.30.0
    hooks:
      - id: gitleaks
        files: ^examples/

  - repo: https://github.com/ansys/pre-commit-hooks
    rev: fd1d6b0b4baeb08e32d4de0909999576695c0433 # v0.5.2
    hooks:
      - id: add-license-headers
        files: '^examples/.*\.(py|bat|html|css|proto)$'
        exclude: '^examples/src/saf/solutions/examples/ui/assets/css/style\.css$'
        args:
          - --custom_license=Apache-2.0

  - repo: https://github.com/google/yamlfmt
    rev: 42486acb2b9ef7aa4850b754d933989bca887349 # v0.20.0
    hooks:
      - id: yamlfmt
        files: ^examples/
        args:
          - "-formatter"
          - "max_line_length=80,retain_line_breaks=true,retain_line_breaks_single=true"
