# Copyright (C) 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc  # type: ignore

from tests.integration.additional_services import greeter_pb2 as greeter__pb2

GRPC_GENERATED_VERSION = "1.64.1"
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = "1.65.0"
SCHEDULED_RELEASE_DATE = "June 25, 2024"
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower  # type: ignore

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in greeter_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
        + f" This warning will become an error in {EXPECTED_ERROR_RELEASE},"
        + f" scheduled for release on {SCHEDULED_RELEASE_DATE}.",
        RuntimeWarning,
    )


class GreeterStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):  # type: ignore
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(  # type: ignore
            "/Greeter/SayHello",
            request_serializer=greeter__pb2.HelloRequest.SerializeToString,  # type: ignore
            response_deserializer=greeter__pb2.HelloReply.FromString,  # type: ignore
            _registered_method=True,
        )


class GreeterServicer:
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):  # type: ignore
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)  # type: ignore
        context.set_details("Method not implemented!")  # type: ignore
        raise NotImplementedError("Method not implemented!")


def add_GreeterServicer_to_server(servicer, server):  # type: ignore
    rpc_method_handlers = {
        "SayHello": grpc.unary_unary_rpc_method_handler(  # type: ignore
            servicer.SayHello,  # type: ignore
            request_deserializer=greeter__pb2.HelloRequest.FromString,  # type: ignore
            response_serializer=greeter__pb2.HelloReply.SerializeToString,  # type: ignore
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("Greeter", rpc_method_handlers)  # type: ignore
    server.add_generic_rpc_handlers((generic_handler,))  # type: ignore
    server.add_registered_method_handlers("Greeter", rpc_method_handlers)  # type: ignore


# This class is part of an EXPERIMENTAL API.
class Greeter:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(  # type: ignore
        request,  # type: ignore
        target,  # type: ignore
        options=(),  # type: ignore
        channel_credentials=None,  # type: ignore
        call_credentials=None,  # type: ignore
        insecure=False,  # type: ignore
        compression=None,  # type: ignore
        wait_for_ready=None,  # type: ignore
        timeout=None,  # type: ignore
        metadata=None,  # type: ignore
    ):  # type: ignore
        return grpc.experimental.unary_unary(  # type: ignore
            request,
            target,
            "/Greeter/SayHello",
            greeter__pb2.HelloRequest.SerializeToString,  # type: ignore
            greeter__pb2.HelloReply.FromString,  # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
