version: 1
disable_existing_loggers: False
formatters:
  fileFormat:
    format: "%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] [trace_id=%(otelTraceID)s
      span_id=%(otelSpanID)s resource.service.name=%(otelServiceName)s]- %(message)s"
handlers:
  rotatingFile:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: fileFormat
    when: "MIDNIGHT"
    filename: "${glow_solution_directory}/logs/ui_server/log_${process_identifier}.log"
    encoding: "utf-8"

root:
  level: WARNING
  handlers: [rotatingFile]

loggers:
  ansys:
    level: INFO
    handlers: [rotatingFile]
    propagate: false
